# Generated by Django 2.0.4 on 2018-04-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='testname', max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
