# Generated by Django 2.0.4 on 2018-04-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table=None,
        ),
    ]
