# Generated by Django 2.0.4 on 2018-04-12 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20180412_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
