# Generated by Django 2.0.4 on 2018-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20180412_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
