# Generated by Django 2.0.4 on 2018-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_enter_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enter',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='price1',
            field=models.IntegerField(default=0),
        ),
    ]
