# Generated by Django 2.0.4 on 2018-04-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20180412_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='price1',
        ),
    ]
