# Generated by Django 2.0.4 on 2018-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_remove_test_price1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='time',
        ),
        migrations.AlterField(
            model_name='test',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
