# Generated by Django 2.0.4 on 2018-04-12 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_subtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enter',
            name='type',
        ),
        migrations.AddField(
            model_name='enter',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enter',
            name='name',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
