# Generated by Django 2.0.4 on 2018-04-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_auto_20180412_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enter',
            new_name='TestEnterLog',
        ),
    ]
