# Generated by Django 2.0.4 on 2018-04-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_auto_20180412_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestEnterLog',
            new_name='Test_Enter_Log',
        ),
    ]
