# Generated by Django 2.0.4 on 2018-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_auto_20180412_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_Enter_Log',
            new_name='TestEnterLog',
        ),
        migrations.AlterModelTable(
            name='testenterlog',
            table='test_enter_log',
        ),
    ]
